const {
  API_CRYPTO_TYPE = '',

  API_CRYPTO_KMS_TYPE = '',
  API_CRYPTO_KMS_NODE_MASTER_KEY = '',
  API_CRYPTO_KMS_NODE_MASTER_IV_HEX = '',
  API_CRYPTO_KMS_AWS_KEY_ID = '',

  API_CRYPTO_REDIS_AUTH_ENABLED = 'false',
  API_CRYPTO_REDIS_CHECK_SERVER_IDENTITY = 'false',
  API_CRYPTO_REDIS_HOST = '',
  API_CRYPTO_REDIS_PORT = '',
  API_CRYPTO_REDIS_KEY_PREFIX = '',
  API_CRYPTO_REDIS_AUTH = '',

  API_CRYPTO_KEY_CACHE_TTL_IN_DAYS = '1',
  API_CRYPTO_CLIENT_IDS = 'BROWSER',

  API_CRYPTO_STATIC_PUBLIC_KEY = '',
  API_CRYPTO_STATIC_PRIVATE_KEY = ''
} = process.env

const REQUIRED_CONFIG = ['API_CRYPTO_TYPE']
let REDIS_CONNECTION_CONFIG

if (API_CRYPTO_TYPE === 'STATIC') {
  REQUIRED_CONFIG.concat([
    'API_CRYPTO_STATIC_PUBLIC_KEY',
    'API_CRYPTO_STATIC_PRIVATE_KEY'
  ])
}

if (API_CRYPTO_TYPE === 'DYNAMIC') {
  REQUIRED_CONFIG.push('API_CRYPTO_KMS_TYPE')

  if (API_CRYPTO_KMS_TYPE === 'NODE ') {
    REQUIRED_CONFIG.push('API_CRYPTO_KMS_NODE_MASTER_KEY')
  }
  if (API_CRYPTO_KMS_TYPE === 'KMS ') {
    REQUIRED_CONFIG.push('API_CRYPTO_KMS_AWS_KEY_ID')
  }

  const REDIS_AUTH_ENABLED = API_CRYPTO_REDIS_AUTH_ENABLED === 'true'
  const REDIS_CHECK_SERVER_IDENTITY = API_CRYPTO_REDIS_CHECK_SERVER_IDENTITY === 'true'
  REQUIRED_CONFIG.concat([
    'API_CRYPTO_REDIS_HOST',
    'API_CRYPTO_REDIS_PORT'
  ])

  if (REDIS_AUTH_ENABLED) {
    REQUIRED_CONFIG.push('API_CRYPTO_REDIS_AUTH')
  }

  REDIS_CONNECTION_CONFIG = {
    host: API_CRYPTO_REDIS_HOST,
    port: API_CRYPTO_REDIS_PORT
  }

  if (REDIS_AUTH_ENABLED) {
    REDIS_CONNECTION_CONFIG.password = API_CRYPTO_REDIS_AUTH
  }

  if (REDIS_CHECK_SERVER_IDENTITY) {
    REDIS_CONNECTION_CONFIG.tls = { checkServerIdentity: () => undefined }
  }
}

REQUIRED_CONFIG.forEach(function (key) {
  if (!process.env[key]) {
    console.error('[Error] Api Crypto Config Missing:', key)
    return process.exit(1)
  }
})

const KEY_CACHE_TTL_IN_DAYS = parseInt(API_CRYPTO_KEY_CACHE_TTL_IN_DAYS, 10)

if (isNaN(KEY_CACHE_TTL_IN_DAYS)) {
  console.error('[Error] Api Crypto Config invalid value for key:', API_CRYPTO_KEY_CACHE_TTL_IN_DAYS)
  process.exit(1)
}

const API_CRYPTO_CONFIG = {
  API_CRYPTO_TYPE,
  CLIENT_IDS: API_CRYPTO_CLIENT_IDS,
  STATIC_PUBLIC_KEY: API_CRYPTO_STATIC_PUBLIC_KEY,
  STATIC_PRIVATE_KEY: API_CRYPTO_STATIC_PRIVATE_KEY,
  API_CRYPTO_KEY_CACHE_TTL_IN_DAYS,

  KMS_CONFIG: {
    KMS_TYPE: API_CRYPTO_KMS_TYPE,
    KMS_NODE_MASTER_KEY: API_CRYPTO_KMS_NODE_MASTER_KEY,
    KMS_NODE_MASTER_IV_HEX: API_CRYPTO_KMS_NODE_MASTER_IV_HEX,
    KMS_AWS_KEY_ID: API_CRYPTO_KMS_AWS_KEY_ID
  },

  REDIS_CONFIG: {
    CONNECTION_CONFIG: REDIS_CONNECTION_CONFIG,
    KEY_PREFIX: API_CRYPTO_REDIS_KEY_PREFIX
  }
}

export default API_CRYPTO_CONFIG
